version: '3.5'

services: 
    frontend:
      image: ltuomola/frontend-example-docker
      ports: 
        - 5000:5000
      build: .
      container_name: frontend
    backend:
      image: ltuomola/backend-example-docker
      ports:
        - 8000:8000
      build: .
      container_name: backend