version: '3.5'

services: 
    proxy:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
    redis:
      image: redis
    db:
      image: postgres
      restart: unless-stopped
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=example
        - POSTGRES_USERNAME=postgres
        # - POSTGRES_DB=database
      container_name: postgres-exercise2.8
    frontend:
      image: ltuomola/frontend-docker
      build: ./frontend-example-docker
      container_name: frontend-exercise2.8
    backend:
      image: ltuomola/backend-docker
      build: ./backend-example-docker
      environment:
        - REDIS=redis
        - DB_USERNAME=postgres
        - DB_PASSWORD=example
        - DB_NAME=postgres
        - DB_HOST=db
      container_name: backend-exercise2.8
      depends_on:
        - db
