version: '3.5'

services: 
    frontend:
      image: ltuomola/frontend-example-docker3-1
      ports: 
        - 5000:5000
      build: ./frontend-example-docker
    backend:
      image: ltuomola/backend-example-docker3-1
      ports:
        - 8000:8000
      build: ./backend-example-docker
