version: '3.5'

services: 
    redis:
      image: redis
    frontend:
      image: ltuomola/frontend-example-docker
      ports: 
        - 5000:5000
      build: .
      container_name: frontend-exercise
    backend:
      image: ltuomola/backend-example-docker
      ports:
        - 8000:8000
      build: .
      environment:
        - REDIS=redis
      container_name: backend-exercise